[package]
name = "polestar-chat"
version = "0.1.0"
edition = "2021"
description = "An AI Q&A chat util written using Ribir, what is a framework written by Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
