[package]
name = "polestar-gui"
version.workspace = true
edition.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polestar-core = { path = "../core" }
ribir = { path = "../../Ribir/ribir", features = ["png"] }
