[package]
name = "polestar_chat_core"
version = "0.0.1"
edition = "2021"
description = "An AI Q&A chat tool written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
derive_builder = "0.12.0"
log = "0.4.20"
sqlx = { version = "0.7.2", features = [
  "sqlite",
  "runtime-tokio",
  "tls-native-tls",
  "uuid",
  "json",
] }
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
home = "0.5.5"
thiserror = "1.0.49"
reqwest = { version = "0.11.18", features = ["json"] }
reqwest-eventsource = "0.5.0"
futures-util = "0.3.28"

[dependencies.uuid]
version = "1.3.3"
features = [
  "v4",       # Lets you generate random UUIDs
  "fast-rng", # Use a faster (but still sufficiently random) RNG
  "serde",
]

[dev-dependencies]
testing_logger = "0.1.1"
